### ISSUE TITLE
Questions weekly reflection dialog

### ISSUE THREAD

**Issue by KristellP** [PerfectFit-project/content-development#110]
- [x] Ask technical team how much work it is to personalize the week number. 
- [x] Depending on answer, decide whether we need to create separate notifications for congratulating on finishing week x of PF
- [x] Check with technical team whether doable to switch to HRS dialog from weekly reflection dialog
- [x] Check with technical team whether doable to edit the HRS graphs when user comes from the weekly reflection dialog

- [x] @Milonvv: overleggen samen hoe het tracken van rook- en beweeggedrag gaat tijdens de voorbereidingsfase (via command 'gerookt' eerder dan via de tracker of anders altijd gesprek opstarten als zij iets tracker via de tracker). Het fijnst zou zijn als zij middels het stuk dialoog in het HRS dialoog bijhouden wat hun HRSs zijn/situatios waarin ze vaak roken. Dat maakt het linkje naar het deel 'look forward' in de weekly reflection makkelijker. 
ANTWOORD: liever via een command tracken dan via de tracker. 
- [x] Met technisch team overleggen hoe het tracken het beste kan worden geïmplementeerd. 

- [x] @Milonvv: In Goal-setting dialog, regel 116. Misschien nog een tijdsspan aangeven voor haalbaarheid. Ooit haalbaar? Of binnen drie maanden? Dat kan nogal uitmaken voor het antwoord. 

- [x] @aversluis1 en @bscheltinga: willen wij van mensen weten of zij medisch gezien niet intensiever kunnen bewegen? En voor die mensen het advies dan niet geven?

- [x] @aversluis1: ook wat te doen als mensen aangeven ziek/gebleseerd te zijn? Op dit moment stopt het dialoog en vragen wij gebruikers aan te geven wanneer ze weer beter zijn. Ook toepassen bij weekly reflection? Zie proposal in #sick

- [x] Can I look together with you for one hour to see what it looks like when you guys code and what it means when you have bugs?

- [x] @bscheltinga: weekly reflection doorlopen en checken of het toereikend is zo. Hoe wordt er een intensiever doel gesteld? Doet de gebruiker dat zelf en helpen wij daarbij? Of stellen wij iets voor? Hoe meet jij intensiviteit?
- [x] @bscheltinga: wanneer komen mensen in groep 2 terecht precies?  
- [x] @bscheltinga: row 152, kan het stappendoel hoger worden dan 8000?
- [x] @bscheltinga: vanaf welk hartslag wordt het gezien als intensieve beweging? Is het 80-90% van HRmax? Zoja, hoe wordt HRmax bepaald?
- [x] @bscheltinga: wat als iemand niet genoeg stappen zet om in groep 2 te zitten, maar wel elke week 1 uur intensief beweegt? Valt hij dan onder groep 1 of 2?

- [x] @Milonvv en @aversluis1: grafiekje stappenoverzicht of tekst zoals nu?
- [x] @Milonvv: doorlopen gebruikers dit dialoog ook in de laatste week? En dan eerst weekly reflection en daarna het closing dialog? Doen we dat dan achter elkaar of zit daar weer een week tussen?

**Comment by KristellP** [comment]
Antwoorden Bouke: 
Je komt in groep 2 van PA wanneer totaal aantal stappen voor de week = 56.000+ EN je op 4 dagen 8000+ stappen hebt gezet. 

Voor intensiteit wordt HR gemeten en voltooide activiteit. 
Streven is 150 activiteitsminuten maar dat is niet het doel aan het einde van PF. Voor weekly reflection dialoog: intensiteitsminuten tellen obv HR en voltooide activiteiten. 
Qua coaching: coachen op zelfde activiteitsniveau + 15 minuten extra intensieve activiteitsminuten waar je HR van omhoog gaat. Dit wordt gemeten o.b.v baseline als zij bij groep 2 komen. Elke week 15 minuten intensieve activiteit erbij. 

Notificaties over stappen: 
GROEP 1 > elke dag. 
GROEP 2 > niet elke dag en meer gericht op intensiteit.
