### ISSUE TITLE
Meta-communications in dialogs

### ISSUE THREAD

**Issue by KristellP** [PerfectFit-project/content-development#32]
Create meta-communications in dialogs:
- [x] Explain purpose of the conversation
- [x] Explain what we do with the information users give
- [x] Explain what the bot is capable of and limitations

**Comment by Milonvv** [comment]
This first point is added to the list of tab '4. Additional dialog features'

**Comment by Milonvv** [comment]
Second and third point are addressed in the introduction video
