### ISSUE TITLE
Track behavior

### ISSUE THREAD

**Issue by KristellP** [PerfectFit-project/content-development#71]
For smoking, two options: in the chat or through the tracker
- [x] Ask technical team whether easier to track only through the tracker or in the chat. 

For PA, only in the chat for PA other than steps/running

**Comment by Milonvv** [comment]
Bouke: 

- Wearables can track many different activities --> would be nice to track as many things as possible automatically using the link with the wearable

- Button for cigarettes is easiest for technical team (if this is not too difficult for content team) -->

- [x] we need to make sure that we explain the use of the tracker for cigarettes to the user

- Notificaties during tracking days to remind them

**Comment by Milonvv** [comment]
Question to Bouke: 

- [x] What specific parameters for PA can we track? (relevant for research protocol)

Antwoord Bouke / Jasper:
- Meten: Stappen (stappenteller) en hartslag
- Baseline bepalen voor stappen duurt 9 dagen
- Het aantal stappen per dag en het stappendoel zal elke dag zichtbaar zijn in de sensor data collector app. We zullen elke dag notificaties sturen met het doel en doel wel/niet bereikt, zodat gebruikers niet actief de sensor data collector app hoeven te bekijken
- Het plan is dat Uni Twente de sensor data collector app zelf maakt. Daarnaast wordt er nog getwijfeld tussen Garmin of Fitbit watch.
- Te moeilijk om andere sportactiviteiten te tracken en advies te geven hiervoor. Daarom in tracking dialoog / goal-setting dialoog duidelijk maken dat alle extra vormen van beweging goed zijn, maar dat wij in dit programma focussen op regelmatig bewegen / elke dag actief zijn door middel van stappen.
